name: Waka Readme

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' 

jobs:
  update-Readme:
    name: WakaReadme DevMetrics  
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          # GITHUB_ACTION: ${{ github.action }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          LANG_COUNT: 10
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_EDITORS: true
          SHOW_LANGUAGE: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_LINES_OF_CODE: true
          SHOW_MASKED_TIME: true
          SHOW_MONTHLY: true
          SHOW_OS: true
          SHOW_PROFILE_VIEWS: false
          SHOW_PROJECTS: true
          SHOW_TIME: true
          SHOW_TIMEZONE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_UPDATED_DATE: true
          STOP_AT_OTHER: false
          SYMBOL_VERSION: 2
          TIME_RANGE: all_time
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
